### ISSUE TITLE
Biblioteca digital

### ISSUE THREAD

**Issue by Programador-jr** [free-educa/books#3]
Encontrei esse repositório por acaso e achei ele muito útil, tive uma ideia e queria colocar ela em prática, fiquei pensando em criar uma página Web contendo todos os livros que atualmente existentes nesse repositório tornando a procura por um livro mais fácil, e gostaria de saber se tenho a sua autorização pra fazer isso

**Comment by JoaoWitu22** [comment]
Seria Legal, Ajudaria A fazer a Página

**Comment by icarlosrigoni** [comment]
Claro, no começo essa foi minha ideia, porem por falta de tempo não consegui fazer a ideia avançar, adoraria ver isso.
