### ISSUE TITLE
Curso Intensivo de Python: Uma Introdução Prática e Baseada em Projetos à Programação

### ISSUE THREAD

**Issue by EmersonJesus** [free-educa/books#31]
[Eric Matthes - Curso Intensivo de Python-Novatec (2016).pdf](https://github.com/free-educa/books/files/12786868/Eric.Matthes.-.Curso.Intensivo.de.Python-Novatec.2016.pdf)

**Comment by Hel777** [comment]
vlw Brother!!

**Comment by Viceleno** [comment]
obrigado

**Comment by Glauco-Glaudston** [comment]
Muito agradecido!

**Comment by EduardoModenes** [comment]
Vlw irmão! 🫱🏼‍🫲🏼
