### ISSUE TITLE
Discussão sobre gerenciamento de arquivos grandes usando Git LFS

### ISSUE THREAD

**Issue by Sir-Vinicius** [free-educa/books#34]
### Problema com arquivos grandes no repositório

Ao tentar contribuir com o livro "A Arte de Game Design" por Jesse Schell para o repositório, enfrentei dificuldades devido ao limite de tamanho de arquivos do GitHub, que impede a adição de arquivos com mais de 100 MB.

### Tentativa de solução com Git LFS

Tentei resolver esse problema utilizando o Git LFS (Git Large File Storage) para gerenciar arquivos grandes. No entanto, também encontrei restrições ao tentar adicionar arquivos grandes em repositórios abertos. O GitHub não permite o uso do Git LFS para armazenar arquivos grandes em forks públicos.

### Pedido de orientação

Gostaria de saber se existe alguma solução alternativa ou política que possa ser implementada para permitir a contribuição de arquivos grandes como este livro, considerando as restrições atuais do GitHub para repositórios públicos.

### Sobre o livro
O livro "A Arte de Game Design - O Livro Original" é uma valiosa contribuição para o projeto, porém seu tamanho excede os limites estabelecidos pelo GitHub. É uma obra escrita por Jesse Schell e possui grande relevância para a comunidade interessada em game design.

Quaisquer sugestões, orientações ou alternativas seriam muito apreciadas.

**Comment by nerdonhub** [comment]
Qual usar compressão? => (.tar | .tar.gz | .tar.bz2 | .bz2 | .zip | .rar)...

**Comment by icarlosrigoni** [comment]
Entendi. O que você pode fazer é tentar usar uma forma de compressão, como o @nerdonhub sugeriu, ou, se ainda estiver muito grande, pode tentar hospedar em outro lugar e adicionar um arquivo .txt com o link de acesso.

**Comment by Sir-Vinicius** [comment]
Segui a orientação de vocês e fiz um pull request com o link para dowload do livro através do mediafire, obrigado.
